/**
 * Machine-readable error codes of the standard error envelope.
 * The frontend must branch on these codes, never on exception strings.
 */
export const ErrorCodes = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  REVISION_CONFLICT: 'REVISION_CONFLICT',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  STATE_CONFLICT: 'STATE_CONFLICT',
  ACTIVE_ATTEMPT_EXISTS: 'ACTIVE_ATTEMPT_EXISTS',
  ATTEMPT_LIMIT_REACHED: 'ATTEMPT_LIMIT_REACHED',
  ADMISSION_CLOSED: 'ADMISSION_CLOSED',
  CAPACITY_REACHED: 'CAPACITY_REACHED',
  DEADLINE_PASSED: 'DEADLINE_PASSED',
  RATE_LIMITED: 'RATE_LIMITED',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
  // Candidate-flow specific, still stable machine codes.
  VIDEO_TOO_LARGE: 'VIDEO_TOO_LARGE',
  VIDEO_TOO_LONG: 'VIDEO_TOO_LONG',
  VIDEO_INVALID_FORMAT: 'VIDEO_INVALID_FORMAT',
  VIDEO_VALIDATION_FAILED: 'VIDEO_VALIDATION_FAILED',
  UPLOAD_INCOMPLETE: 'UPLOAD_INCOMPLETE',
  PHOTO_TOO_LARGE: 'PHOTO_TOO_LARGE',
  PHOTO_INVALID_FORMAT: 'PHOTO_INVALID_FORMAT',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
